name: Keep Alive - School Hours
on:
  schedule:
    # Ping every 10 minutes from 7 AM to 10 PM UTC
    # Adjust timezone as needed - this is for UTC
    - cron: '*/10 7-22 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        run: echo "Current time is $(date)"
        
      - name: Ping St Mary's Portal
        run: |
          echo "Pinging St Mary's Portal to keep it awake..."
          curl -f https://stmarys-f2k3.onrender.com/api/test || echo "Ping failed, but continuing..."
          echo "Ping completed at $(date)"
        
      - name: Log status
        run: echo "Keep-alive job completed successfully"
